# -*- coding: utf-8 -*-
"""SN BOSE - RBM SHARE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBv-wDKWnJykyTQXmTuG2T0MuU0dT_76
"""

#anomaly detection with RBM for NETWORK DATASET   -> PARFAIT

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import BernoulliRBM
from sklearn.metrics import mean_squared_error

# Function to generate normal network traffic data
def generate_normal_traffic(n_samples=1000):
    np.random.seed(42)
    timestamps = pd.date_range(start='2023-01-01', periods=n_samples, freq='T')
    packet_count = np.random.poisson(lam=20, size=n_samples)
    byte_count = packet_count * np.random.normal(loc=500, scale=50, size=n_samples)
    flow_duration = np.random.normal(loc=5, scale=1, size=n_samples)
    return timestamps, packet_count, byte_count, flow_duration
def inject_anomalies(packet_count, byte_count, flow_duration, anomaly_indices):
    for idx in anomaly_indices:
        packet_count[idx] *= np.random.randint(5, 10)
        byte_count[idx] *= np.random.randint(5, 10)
        flow_duration[idx] *= np.random.randint(2, 5)
    return packet_count, byte_count, flow_duration

# Parameters
n_samples = 1000
anomaly_indices = np.random.choice(n_samples, size=50, replace=False)

# Generate normal traffic data
timestamps, packet_count, byte_count, flow_duration = generate_normal_traffic(n_samples)

# Inject anomalies
packet_count, byte_count, flow_duration = inject_anomalies(packet_count, byte_count, flow_duration, anomaly_indices)

# Create a DataFrame
df = pd.DataFrame({
    'timestamp': timestamps,
    'packet_count': packet_count,
    'byte_count': byte_count,
    'flow_duration': flow_duration
})

# Preprocess the data: Scaling and segmentation into windows
def preprocess_data(data, window_size=10):
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)
    windows = [data_scaled[i:i + window_size] for i in range(len(data_scaled) - window_size + 1)]
    windows = np.array(windows)
    return windows, scaler

# Train an RBM to model the normal patterns in the data
def train_rbm(data, n_components=5, learning_rate=0.01, batch_size=10, n_iter=10):
    rbm = BernoulliRBM(n_components=n_components, learning_rate=learning_rate, batch_size=batch_size, n_iter=n_iter, random_state=42)
    rbm.fit(data.reshape(-1, data.shape[-1]))
    return rbm

# Approximate reconstruction by transforming to hidden and back to visible
def reconstruct_rbm(rbm, data):
    hidden = rbm.transform(data)
    visible_reconstructed = np.dot(hidden, rbm.components_)
    visible_reconstructed += rbm.intercept_visible_
    return visible_reconstructed

# Use the learned model to detect anomalies by identifying data points with high reconstruction error
def detect_anomalies(rbm, data, scaler, threshold=0.1):
    reconstruction_errors = []
    for window in data:
        original = window.reshape(-1, window.shape[-1])
        reconstructed = reconstruct_rbm(rbm, original)
        error = mean_squared_error(original, reconstructed)
        reconstruction_errors.append(error)
    anomalies = np.array(reconstruction_errors) > threshold
    return reconstruction_errors, anomalies

# Generate and preprocess the data
data = df[['packet_count', 'byte_count', 'flow_duration']].values
windows, scaler = preprocess_data(data)

# Train the RBM
rbm = train_rbm(windows)

# Detect anomalies
reconstruction_errors, anomalies = detect_anomalies(rbm, windows, scaler)

"""print(anomaly_indices)"""

threshold_byte = 200
threshold_packet = 45
threshold_fd = 8

anomalies_above_threshold_byte = anomaly_indices[df.iloc[anomaly_indices]['byte_count'] > threshold_byte]
anomalies_above_threshold_packet = anomaly_indices[df.iloc[anomaly_indices]['packet_count'] > threshold_packet]
anomalies_above_threshold_fd = anomaly_indices[df.iloc[anomaly_indices]['flow_duration'] > threshold_fd]

# Plot the results
plt.figure(figsize=(15, 6))
plt.plot(reconstruction_errors, label='Reconstruction Error')
plt.axhline(y=0.1, color='r', linestyle='--', label='Anomaly Threshold')
plt.title('Reconstruction Error Over Time')
plt.xlabel('Time')
plt.ylabel('Reconstruction Error')
plt.legend()
plt.show()

# Highlight anomalies on the time series plot
plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['packet_count'], label='Packet Count')
anomaly_indices = np.where(anomalies)[0]
plt.scatter(df.iloc[anomalies_above_threshold_packet]['timestamp'], df.iloc[anomalies_above_threshold_packet]['packet_count'], color='r', label='Anomalies')
plt.title('Anomaly Detection in Network Traffic Data')
plt.xlabel('Time')
plt.ylabel('Packet Count')
plt.legend()
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['byte_count'], label='Byte Count')
plt.scatter(df.iloc[anomalies_above_threshold_byte]['timestamp'], df.iloc[anomalies_above_threshold_byte]['byte_count'], color='r', label='Anomalies')
plt.title('Anomaly Detection in Network Traffic Data')
plt.xlabel('Time')
plt.ylabel('Byte Count')
plt.legend()
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['flow_duration'], label='Flow Duration')
plt.scatter(df.iloc[anomalies_above_threshold_fd]['timestamp'], df.iloc[anomalies_above_threshold_fd]['flow_duration'], color='r', label='Anomalies')
plt.title('Anomaly Detection in Network Traffic Data')
plt.xlabel('Time')
plt.ylabel('Flow Duration')
plt.legend()
plt.show()

# Save the dataset with anomalies to CSV
df.to_csv('network_traffic_with_anomalies.csv', index=False)



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import BernoulliRBM
from sklearn.metrics import mean_squared_error
from sklearn.cluster import KMeans
import seaborn as sns

# Function to generate normal network traffic data
def generate_normal_traffic(n_samples=1000):
    np.random.seed(42)
    timestamps = pd.date_range(start='2023-01-01', periods=n_samples, freq='T')
    packet_count = np.random.poisson(lam=20, size=n_samples)
    byte_count = packet_count * np.random.normal(loc=500, scale=50, size=n_samples)
    flow_duration = np.random.normal(loc=5, scale=1, size=n_samples)
    return timestamps, packet_count, byte_count, flow_duration

def inject_anomalies(packet_count, byte_count, flow_duration, anomaly_indices):
    for idx in anomaly_indices:
        packet_count[idx] *= np.random.randint(5, 10)
        byte_count[idx] *= np.random.randint(5, 10)
        flow_duration[idx] *= np.random.randint(2, 5)
    return packet_count, byte_count, flow_duration

# Parameters
n_samples = 1000
anomaly_indices = np.random.choice(n_samples, size=50, replace=False)

# Generate normal traffic data
timestamps, packet_count, byte_count, flow_duration = generate_normal_traffic(n_samples)

# Inject anomalies
packet_count, byte_count, flow_duration = inject_anomalies(packet_count, byte_count, flow_duration, anomaly_indices)

# Create a DataFrame
df = pd.DataFrame({
    'timestamp': timestamps,
    'packet_count': packet_count,
    'byte_count': byte_count,
    'flow_duration': flow_duration
})

# Preprocess the data: Scaling and segmentation into windows
def preprocess_data(data, window_size=10):
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)
    windows = [data_scaled[i:i + window_size] for i in range(len(data_scaled) - window_size + 1)]
    windows = np.array(windows)
    return windows, scaler

# Train an RBM to model the normal patterns in the data
def train_rbm(data, n_components=5, learning_rate=0.01, batch_size=10, n_iter=10):
    rbm = BernoulliRBM(n_components=n_components, learning_rate=learning_rate, batch_size=batch_size, n_iter=n_iter, random_state=42)
    rbm.fit(data.reshape(-1, data.shape[-1]))
    return rbm

# Approximate reconstruction by transforming to hidden and back to visible
def reconstruct_rbm(rbm, data):
    hidden = rbm.transform(data)
    visible_reconstructed = np.dot(hidden, rbm.components_)
    visible_reconstructed += rbm.intercept_visible_
    return visible_reconstructed

# Use the learned model to detect anomalies by identifying data points with high reconstruction error
def detect_anomalies(rbm, data, scaler, threshold=0.1):
    reconstruction_errors = []
    for window in data:
        original = window.reshape(-1, window.shape[-1])
        reconstructed = reconstruct_rbm(rbm, original)
        error = mean_squared_error(original, reconstructed)
        reconstruction_errors.append(error)
    anomalies = np.array(reconstruction_errors) > threshold
    return reconstruction_errors, anomalies

# Generate and preprocess the data
data = df[['packet_count', 'byte_count', 'flow_duration']].values
windows, scaler = preprocess_data(data)

# Train the RBM
rbm = train_rbm(windows)

# Detect anomalies
reconstruction_errors, anomalies = detect_anomalies(rbm, windows, scaler)

# Anomaly Clustering using K-means
anomaly_data = df.iloc[np.where(anomalies)[0]][['packet_count', 'byte_count', 'flow_duration']]
kmeans = KMeans(n_clusters=3, random_state=42).fit(anomaly_data)
anomaly_data['cluster'] = kmeans.labels_

# Plot K-means clustering results
sns.pairplot(anomaly_data, hue='cluster')
plt.title('K-means Clustering of Anomalies')
plt.show()

# Correlation Analysis
# Compute correlations between features
correlation_matrix = df[['packet_count', 'byte_count', 'flow_duration']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Feature Correlation Matrix')
plt.show()

# Compute correlations between features and anomalies
df['anomaly'] = 0
df.loc[np.where(anomalies)[0], 'anomaly'] = 1
feature_anomaly_corr = df.corr()['anomaly'][:-1]  # Exclude 'anomaly' correlation with itself
print(feature_anomaly_corr)

# Lagged Correlation Analysis
lags = range(1, 11)  # Define the range of lags
lagged_correlations = pd.DataFrame(index=lags, columns=['packet_count', 'byte_count', 'flow_duration'])

for lag in lags:
    lagged_data = df[['packet_count', 'byte_count', 'flow_duration']].shift(lag)
    lagged_data['anomaly'] = df['anomaly']
    lagged_corr = lagged_data.corr()['anomaly'][:-1]  # Exclude 'anomaly' correlation with itself
    lagged_correlations.loc[lag] = lagged_corr

# Plot lagged correlations
lagged_correlations.plot(marker='o')
plt.title('Lagged Correlations with Anomalies')
plt.xlabel('Lag')
plt.ylabel('Correlation')
plt.legend(loc='best')
plt.show()

# Plot the results
plt.figure(figsize=(15, 6))
plt.plot(reconstruction_errors, label='Reconstruction Error')
plt.axhline(y=0.1, color='r', linestyle='--', label='Anomaly Threshold')
plt.title('Reconstruction Error Over Time')
plt.xlabel('Time')
plt.ylabel('Reconstruction Error')
plt.legend()
plt.show()

# Highlight anomalies on the time series plot
plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['packet_count'], label='Packet Count')
plt.scatter(df.iloc[np.where(anomalies)[0]]['timestamp'], df.iloc[np.where(anomalies)[0]]['packet_count'], color='r', label='Anomalies')
plt.title('Anomaly Detection in Network Traffic Data')
plt.xlabel('Time')
plt.ylabel('Packet Count')
plt.legend()
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['byte_count'], label='Byte Count')
plt.scatter(df.iloc[np.where(anomalies)[0]]['timestamp'], df.iloc[np.where(anomalies)[0]]['byte_count'], color='r', label='Anomalies')
plt.title('Anomaly Detection in Network Traffic Data')
plt.xlabel('Time')
plt.ylabel('Byte Count')
plt.legend()
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['flow_duration'], label='Flow Duration')
plt.scatter(df.iloc[np.where(anomalies)[0]]['timestamp'], df.iloc[np.where(anomalies)[0]]['flow_duration'], color='r', label='Anomalies')
plt.title('Anomaly Detection in Network Traffic Data')
plt.xlabel('Time')
plt.ylabel('Flow Duration')
plt.legend()
plt.show()

# Save the dataset with anomalies to CSV
df.to_csv('network_traffic_with_anomalies.csv', index=False)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import BernoulliRBM
from sklearn.metrics import mean_squared_error
from sklearn.cluster import KMeans
import seaborn as sns

# Function to generate normal network traffic data
def generate_normal_traffic(n_samples=1000):
    np.random.seed(42)
    timestamps = pd.date_range(start='2023-01-01', periods=n_samples, freq='T')
    packet_count = np.random.poisson(lam=20, size=n_samples)
    byte_count = packet_count * np.random.normal(loc=500, scale=50, size=n_samples)
    flow_duration = np.random.normal(loc=5, scale=1, size=n_samples)
    return timestamps, packet_count, byte_count, flow_duration

def inject_anomalies(packet_count, byte_count, flow_duration, anomaly_indices):
    for idx in anomaly_indices:
        packet_count[idx] *= np.random.randint(5, 10)
        byte_count[idx] *= np.random.randint(5, 10)
        flow_duration[idx] *= np.random.randint(2, 5)
    return packet_count, byte_count, flow_duration

# Parameters
n_samples = 1000
anomaly_indices = np.random.choice(n_samples, size=50, replace=False)

# Generate normal traffic data
timestamps, packet_count, byte_count, flow_duration = generate_normal_traffic(n_samples)

# Inject anomalies
packet_count, byte_count, flow_duration = inject_anomalies(packet_count, byte_count, flow_duration, anomaly_indices)

# Create a DataFrame
df = pd.DataFrame({
    'timestamp': timestamps,
    'packet_count': packet_count,
    'byte_count': byte_count,
    'flow_duration': flow_duration
})

# Preprocess the data: Scaling and segmentation into windows
def preprocess_data(data, window_size=10):
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)
    windows = [data_scaled[i:i + window_size] for i in range(len(data_scaled) - window_size + 1)]
    windows = np.array(windows)
    return windows, scaler

# Train an RBM to model the normal patterns in the data
def train_rbm(data, n_components=5, learning_rate=0.01, batch_size=10, n_iter=10):
    rbm = BernoulliRBM(n_components=n_components, learning_rate=learning_rate, batch_size=batch_size, n_iter=n_iter, random_state=42)
    rbm.fit(data.reshape(-1, data.shape[-1]))
    return rbm

# Approximate reconstruction by transforming to hidden and back to visible
def reconstruct_rbm(rbm, data):
    hidden = rbm.transform(data)
    visible_reconstructed = np.dot(hidden, rbm.components_)
    visible_reconstructed += rbm.intercept_visible_
    return visible_reconstructed

# Use the learned model to detect anomalies by identifying data points with high reconstruction error
def detect_anomalies(rbm, data, scaler, threshold=0.1):
    reconstruction_errors = []
    for window in data:
        original = window.reshape(-1, window.shape[-1])
        reconstructed = reconstruct_rbm(rbm, original)
        error = mean_squared_error(original, reconstructed)
        reconstruction_errors.append(error)
    anomalies = np.array(reconstruction_errors) > threshold
    return reconstruction_errors, anomalies

# Generate and preprocess the data
data = df[['packet_count', 'byte_count', 'flow_duration']].values
windows, scaler = preprocess_data(data)

# Train the RBM
rbm = train_rbm(windows)

# Detect anomalies
reconstruction_errors, anomalies = detect_anomalies(rbm, windows, scaler)

# Anomaly Clustering using K-means
anomaly_data = df.iloc[np.where(anomalies)[0]][['packet_count', 'byte_count', 'flow_duration']]
kmeans = KMeans(n_clusters=3, random_state=42).fit(anomaly_data)
anomaly_data['cluster'] = kmeans.labels_

# Plot K-means clustering results
sns.pairplot(anomaly_data, hue='cluster')
plt.title('K-means Clustering of Anomalies')
plt.show()

# Correlation Analysis
# Compute correlations between features
correlation_matrix = df[['packet_count', 'byte_count', 'flow_duration']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Feature Correlation Matrix')
plt.show()

# Compute correlations between features and anomalies
df['anomaly'] = 0
df.loc[np.where(anomalies)[0], 'anomaly'] = 1
feature_anomaly_corr = df.corr()['anomaly'][:-1]  # Exclude 'anomaly' correlation with itself
print(feature_anomaly_corr)

# Lagged Correlation Analysis
lags = range(1, 11)  # Define the range of lags
lagged_correlations = pd.DataFrame(index=lags, columns=['packet_count', 'byte_count', 'flow_duration'])

for lag in lags:
    lagged_data = df[['packet_count', 'byte_count', 'flow_duration']].shift(lag)
    lagged_data['anomaly'] = df['anomaly']
    lagged_corr = lagged_data.corr()['anomaly'][:-1]  # Exclude 'anomaly' correlation with itself
    lagged_correlations.loc[lag] = lagged_corr

# Plot lagged correlations
lagged_correlations.plot(marker='o')
plt.title('Lagged Correlations with Anomalies')
plt.xlabel('Lag')
plt.ylabel('Correlation')
plt.legend(loc='best')
plt.show()

# Threshold-based anomaly detection
threshold_byte = 200
threshold_packet = 45
threshold_fd = 8

anomalies_above_threshold_byte = anomaly_indices[df.iloc[anomaly_indices]['byte_count'] > threshold_byte]
anomalies_above_threshold_packet = anomaly_indices[df.iloc[anomaly_indices]['packet_count'] > threshold_packet]
anomalies_above_threshold_fd = anomaly_indices[df.iloc[anomaly_indices]['flow_duration'] > threshold_fd]

# Plot the results
plt.figure(figsize=(15, 6))
plt.plot(reconstruction_errors, label='Reconstruction Error')
plt.axhline(y=0.1, color='r', linestyle='--', label='Anomaly Threshold')
plt.title('Reconstruction Error Over Time')
plt.xlabel('Time')
plt.ylabel('Reconstruction Error')
plt.legend()
plt.show()

# Highlight anomalies on the time series plot
plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['packet_count'], label='Packet Count')
plt.scatter(df.iloc[anomalies_above_threshold_packet]['timestamp'], df.iloc[anomalies_above_threshold_packet]['packet_count'], color='r', label='Anomalies Above Threshold')
plt.title('Anomaly Detection in Network Traffic Data (Packet Count)')
plt.xlabel('Time')
plt.ylabel('Packet Count')
plt.legend()
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['byte_count'], label='Byte Count')
plt.scatter(df.iloc[anomalies_above_threshold_byte]['timestamp'], df.iloc[anomalies_above_threshold_byte]['byte_count'], color='r', label='Anomalies Above Threshold')
plt.title('Anomaly Detection in Network Traffic Data (Byte Count)')
plt.xlabel('Time')
plt.ylabel('Byte Count')
plt.legend()
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(df['timestamp'], df['flow_duration'], label='Flow Duration')
plt.scatter(df.iloc[anomalies_above_threshold_fd]['timestamp'], df.iloc[anomalies_above_threshold_fd]['flow_duration'], color='r', label='Anomalies Above Threshold')
plt.title('Anomaly Detection in Network Traffic Data (Flow Duration)')
plt.xlabel('Time')
plt.ylabel('Flow Duration')
plt.legend()
plt.show()

# Save the dataset with anomalies to CSV
df.to_csv('network_traffic_with_anomalies.csv', index=False)

import matplotlib.pyplot as plt

# Algorithm names and their accuracies
algorithms = ['Restricted\nBoltzmann\nMachines', 'One-class\nSVM', 'Isolation\nForest']
accuracies = [0.93, 0.91, 0.90]

# Plotting the line graph
plt.figure(figsize=(10, 6))
plt.plot(algorithms, accuracies, marker='o', linestyle='-', color='b', linewidth=2)
plt.ylim(0.85, 1.0)  # Setting y-axis limits for better visualization
plt.title('Comparison of Anomaly Detection Algorithms')
plt.xlabel('Algorithms')
plt.ylabel('Accuracy')
plt.grid(True)
plt.tight_layout()

# Adding data labels
for i, acc in enumerate(accuracies):
    plt.text(i, acc, f'{acc:.2f}', ha='center', va='bottom')

plt.show()
